- name: Install postgresql 16
  dnf:
    name: postgresql16
    state: present

- name: Add connection line for root
  template:
    src: connection_line.pgpass.j2
    dest: /root/.pgpass
    mode: '0600'

- name: Setup pg_basebackup cron
  ansible.builtin.cron:
    name: "pg_basebackup"
    minute: "0"
    hour: "2"
    job: "pg_basebackup -h {{ pgs_vrrp }} -p 5000 -D /backups/$(date +\\%F) -U replicator -Ft -z -P"

- name: Add rotate of files to crontab file
  ansible.builtin.cron:
    name: "find"
    minute: "0"
    hour: "3"
    job: "find /backups -type d -mtime +7 -exec rm -rf {} \ "
