- name: Test
  hosts: all
  tasks:
    - name: Gather facts on listening ports
      community.general.listen_ports_facts:

    - name: start firewalld
      service:
        name: firewalld
        state: started
        enabled: yes
      become: true

    - name: Add TCP ports to firewall
      firewalld:
        port: "{{ item }}/tcp"
        state: enabled
        immediate: true
        permanent: true
      loop: "{{ ansible_facts.tcp_listen  | map(attribute='port') | sort | list }}"
      register: ports_added_to_firewalld
      become: true

    - name: Add UDP ports to firewall
      firewalld:
        port: "{{ item }}/udp"
        state: enabled
        immediate: true
        permanent: true
      loop: "{{ ansible_facts.udp_listen  | map(attribute='port') | sort | list }}"
      register: ports_added_to_firewalld
      become: true